version: '3.8'

services:
  attendance-db:
    env_file: ./.env
    image: mongo:4.4.23
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${SIRIUS_X_ATTENDANCE_MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${SIRIUS_X_ATTENDANCE_MONGO_USERNAME}
    ports:
      - ${SIRIUS_X_ATTENDANCE_DB_PORT}:27017
    restart: always
    volumes:
      - sirius_volume:/data/db
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - shared_network

  attendance-server:
    env_file: .env
    build: .
    restart: always
    ports:
      - "3002:3002"
    environment:
      SIRIUS_X_ATTENDANCE_MONGO_HOST: host.docker.internal
    depends_on:
      - attendance-db
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - shared_network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus # Shared Volume
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"
      - "--storage.tsdb.min-block-duration=10m"
      - "--storage.tsdb.max-block-duration=10m"
    networks:
      - shared_network

  node_exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    networks:
      - shared_network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - shared_network

volumes:
  sirius_volume:
  prometheus-data: # Definition for the shared volume

networks:
  shared_network:
#    driver: bridge
    external: true