global:
  scrape_interval: 15s
  external_labels:
    monitor: 'my-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'        # changed from node_exporter to node-exporter
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']   # ← hyphen!

  - job_name: 'attendance-server'
    static_configs:
      - targets: ['attendance-server:3002']
    metrics_path: '/metrics'
    scrape_interval: 5s
