global:
  scrape_interval: 15s
  external_labels:
    monitor: 'my-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'attendance-back-attendance-server-1'
    static_configs:
      - targets: ['attendance-back-attendance-server-1:3002']