apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      external_labels:
        monitor: "my-monitor"

    scrape_configs:
    - job_name: "prometheus"
      scrape_interval: 5s
      static_configs:
      - targets: ["localhost:9090"]

    - job_name: "node-exporter"
      scrape_interval: 5s
      static_configs:
      - targets: ["node-exporter:9100"]

    - job_name: "attendance-server"
      scrape_interval: 5s
      metrics_path: "/metrics"
      static_configs:
      - targets: ["attendance-server:3002"]
